import subprocess
import os
import sys
import time
from pathlib import Path

class LipSyncGenerator:
    def __init__(self, wav2lip_path=None):
        if wav2lip_path is None:
            backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            self.wav2lip_path = os.path.join(backend_dir, 'Wav2Lip')
        else:
            self.wav2lip_path = wav2lip_path

        self.checkpoint_path = os.path.join(
            self.wav2lip_path,
            'checkpoints',
            'wav2lip_gan.pth'
        )

    def check_installation(self):
        if not os.path.exists(self.wav2lip_path):
            return False, f"Wav2Lip directory not found at: {self.wav2lip_path}"
        if not os.path.exists(self.checkpoint_path):
            return False, f"Wav2Lip checkpoint not found: {self.checkpoint_path}"
        return True, "OK"

    def generate_video(
        self,
        face_path,
        audio_path,
        output_path,
        fps=24,
        resize_factor=1,
        quality='high'
    ):
        # Validate install
        ok, msg = self.check_installation()
        if not ok:
            return None, msg

        # Resolve absolute paths
        def make_abs(p):
            p = Path(p)
            if p.is_absolute():
                return p.resolve()
            return (Path(__file__).parent.parent / p).resolve()

        face_abs = make_abs(face_path)
        audio_abs = make_abs(audio_path)
        output_abs = make_abs(output_path)

        if not face_abs.exists(): return None, f"Face not found: {face_abs}"
        if not audio_abs.exists(): return None, f"Audio not found: {audio_abs}"

        output_abs.parent.mkdir(parents=True, exist_ok=True)
        inference_script = os.path.join(self.wav2lip_path, 'inference.py')

        base_command = [
            sys.executable,
            inference_script,
            '--checkpoint_path', self.checkpoint_path,
            '--face', str(face_abs),
            '--audio', str(audio_abs),
            '--outfile', str(output_abs),
            '--fps', str(fps),
            '--resize_factor', str(resize_factor),
        ]

        # Quality tuning
        if quality == 'high':
            base_command += ['--pads', '0', '20', '0', '0', '--nosmooth']
        elif quality == 'medium':
            base_command += ['--pads', '0', '10', '0', '0']
        else:
            base_command += ['--pads', '0', '5', '0', '0']

        max_attempts = 4
        current_resize = resize_factor
        current_batch = 128
        last_error = ""

        for attempt in range(max_attempts):
            try:
                cmd = list(base_command)
                # Dynamic params
                cmd += ['--wav2lip_batch_size', str(current_batch)]
                cmd += ['--face_det_batch_size', str(max(1, current_batch // 4))]

                print(f"\n[Wav2Lip] Attempt {attempt+1} (Resize: {current_resize}, Batch: {current_batch})")

                result = subprocess.run(
                    cmd,
                    cwd=self.wav2lip_path,
                    stdout=None,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=1800
                )

                if result.returncode == 0 and output_abs.exists():
                    print("[SUCCESS] Raw video generated by Wav2Lip")

                    # ─────────────────────────────────────
                    # 🔥 ROBUST FPS CORRECTION VIA FFMPEG
                    # ─────────────────────────────────────
                    try:
                        fixed_path = output_abs.with_name(output_abs.stem + "_fixed.mp4")
                        ffmpeg_cmd = [
                            "ffmpeg", "-y", "-i", str(output_abs),
                            "-r", str(fps),              # FORCE FPS
                            "-c:v", "libx264",
                            "-preset", "ultrafast",
                            "-pix_fmt", "yuv420p",
                            "-c:a", "aac",
                            str(fixed_path)
                        ]
                        print("[FIX] Applying FPS correction via FFmpeg...")
                        fix_res = subprocess.run(ffmpeg_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                        
                        if fix_res.returncode == 0 and fixed_path.exists():
                            os.replace(fixed_path, output_abs)
                            print("[FIX] FPS correction applied successfully")
                    except Exception as fe:
                        print(f"[WARNING] FPS correction failed: {fe}")

                    return str(output_abs), "Success"

                # Failure handling
                last_error = result.stderr or "Unknown error"
                print(f"[WARNING] Wav2Lip Attempt {attempt+1} failed: {last_error[:150]}")

                # Adaptive recovery
                if attempt == 0:
                    current_resize = 2; current_batch = 64
                elif attempt == 1:
                    current_resize = 4; current_batch = 32
                elif attempt == 2:
                    current_resize = 4; current_batch = 8
                elif attempt == 3:
                    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
                    current_batch = 1

                time.sleep(2)

            except Exception as e:
                last_error = str(e)
                print(f"[ERROR] Wav2Lip Exception: {e}")

            finally:
                if "CUDA_VISIBLE_DEVICES" in os.environ:
                    del os.environ["CUDA_VISIBLE_DEVICES"]

        return None, f"LipSync failed after {max_attempts} attempts: {last_error}"